name: ZIP File

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Files
        run: |
          mkdir socialswitch-v0.5.2-chrome
          cp chrome/background.js chrome/popup.js chrome/popup.html chrome/supported.html chrome/style.css chrome/manifest.json socialswitch-v0.5.2-chrome/
          cp -r chrome/icons/ socialswitch-v0.5.2-chrome/
          mkdir socialswitch-v0.5.2-firefox
          cp firefox/background.js firefox/popup.js firefox/popup.html firefox/supported.html firefox/style.css firefox/manifest.json socialswitch-v0.5.2-firefox/
          cp -r firefox/icons/ socialswitch-v0.5.2-firefox/

      - name: Upload Chrome Artifact
        uses: actions/upload-artifact@v4
        with:
          name: socialswitch-v0.5.2-chrome
          path: socialswitch-v0.5.2-chrome

      - name: Upload Firefox Artifact
        uses: actions/upload-artifact@v4
        with:
          name: socialswitch-v0.5.2-firefox
          path: socialswitch-v0.5.2-firefox
