name: ZIP Files

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Files
        run: |
          mkdir socialswitch-v1.0-chrome
          cp chrome/background.js chrome/manifest.json chrome/popup.js chrome/popup.html chrome/support.html chrome/style.css socialswitch-v1.0-chrome/
          cp -r chrome/icons/ socialswitch-v1.0-chrome/
          mkdir socialswitch-v1.0-firefox
          cp firefox/background.js firefox/manifest.json firefox/popup.js chrome/popup.html chrome/support.html chrome/style.css socialswitch-v1.0-firefox/
          cp -r chrome/icons/ socialswitch-v1.0-firefox/
          mkdir socialswitch-v1.0-firefox-android
          cp firefox-android/manifest.json firefox-android/popup.html firefox-android/support.html firefox-android/style.css firefox-android/style-firefox-android.css firefox/background.js firefox/popup.js socialswitch-v1.0-firefox-android/
          cp -r chrome/icons/ socialswitch-v1.0-firefox-android/

      - name: Upload Chrome Artifact
        uses: actions/upload-artifact@v4
        with:
          name: socialswitch-v1.0-chrome
          path: socialswitch-v1.0-chrome

      - name: Upload Firefox Artifact
        uses: actions/upload-artifact@v4
        with:
          name: socialswitch-v1.0-firefox
          path: socialswitch-v1.0-firefox

      - name: Upload Firefox for Android Artifact
        uses: actions/upload-artifact@v4
        with:
          name: socialswitch-v1.0-firefox-android
          path: socialswitch-v1.0-firefox-android
