name: ZIP File

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Files
        run: |
          mkdir socialswitch-v0.5.2
          cp src/background.js src/popup.js src/popup.html src/supported.html src/style.css src/manifest.json socialswitch-v0.5.2/
          cp -r src/icons/ socialswitch-v0.5.2/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: socialswitch-v0.5.2
          path: socialswitch-v0.5.2
