name: Zip File

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Files
        run: |
          mkdir socialswitch-v0.5.1
          cp background.js popup.js popup.html supported.html style.css manifest.json socialswitch-v0.5.1/
          cp -r icons/ socialswitch-v0.5.1/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: socialswitch-v0.5.1
          path: socialswitch-v0.5.1
