name: Zip File

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Zip file
        run: |
          mkdir socialswitch-v0.5
          cp background.js popup.js popup.html supported.html style.css manifest.json socialswitch-v0.5/
          cp -r icons/ socialswitch-v0.5/
          zip -r socialswitch-v0.5.zip socialswitch-v0.5

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: socialswitch-v0.5
          path: socialswitch-v0.5.zip
